CREATE TABLE [auth].[User]
(
	[UserId] UNIQUEIDENTIFIER NOT NULL,
	[Name] NVARCHAR(512) NOT NULL,
	[EmailAddressId] UNIQUEIDENTIFIER NOT NULL,
	[IsActive] BIT NOT NULL,
	[CreateTimestamp] DATETIME2(4) CONSTRAINT [DF_User_CreateTimestamp] DEFAULT(SYSUTCDATETIME()) NOT NULL,
	[UpdateTimestamp] DATETIME2(4) CONSTRAINT [DF_User_UpdateTimestamp] DEFAULT(SYSUTCDATETIME()) NOT NULL,
	CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED ([UserId])
)

GO

CREATE UNIQUE INDEX [IX_User_Name] ON [auth].[User] ([Name])
